### ISSUE TITLE
Error in select_genes(x, params) : length(sel_genes) > 0 is not TRUE

### ISSUE THREAD

**Issue by lkmklsmn** [wmacnair/psupertime#1]
Hi,

I am trying out psupertime on Dropseq scRNAseq data (pretty shallow). 
All of my genes are excluded even though the all genes are detected in more than 10% of cells:

`tpm <- scater::calculateCPM(cm)`
`genes <- names(which(apply(tpm, 1, function(x) mean(x > 0)) > 0.1))`
`res <- psupertime(x = t(tpm), y = md$grouping, sel_genes = "list", gene_list = genes, min_expression = 0.1)`

> 300 genes have insufficient expression and will not be used as input to psupertime
> Error in select_genes(x, params) : length(sel_genes) > 0 is not TRUE

What additional parameters define the gene selection?

**Comment by lkmklsmn** [comment]
Found my mistake: I did not have a logcounts assay. Sorry to bother.

**Comment by wmacnair** [comment]
Hi @lkmklsmn, thanks for raising this.

From the code you posted, `psupertime` should be running the matrix rather than `sce` version, so the logcounts assay shouldn't make any difference. Let me check whether there's an issue with the logic somewhere.
