### ISSUE TITLE
Using 'hvg' option Error in .local(x, ...) :    need at least 2 points for non-parametric curve fitting

### ISSUE THREAD

**Issue by aron0093** [wmacnair/psupertime#12]
Error while using the 'hvg' option. Input is a matrix not SCE object. Code and data to reproduce issue below.

[mwe_psupertime.zip](https://github.com/wmacnair/psupertime/files/3751007/mwe_psupertime.zip)

```
>psupertime(x = as.matrix(data, rownames = TRUE), y = labels, sel_genes = 'hvg', smooth=TRUE, n_folds = 3)
converting y to a factor. label ordering used for training psupertime is:
3, 4, 5, 6
using default parameters to identify highly variable genes
identifying highly variable genes
Error in .local(x, ...) : 
  need at least 2 points for non-parametric curve fitting

**Comment by aron0093** [comment]
I don't face this error anymore. it was solved by encoding the labels as categories, i.e.

`factor(labels)`

`labels` itself is a vector of numerical values. I would suggest that this could be implemented as part of the data processing within psupertime.

**Comment by wmacnair** [comment]
Hmm. This doesn't quite make sense for me. I assume the error is in the HVG identification bit, which comes from `scran`. So I'm surprised that changing the labels to factors fixes this. Especially since `psupertime` converts it to a factor itself... I'll reopen so that I can check this.

**Comment by aron0093** [comment]
You are right! I didn't realise that I had resolved this particular error and that without using `factor(labels)` I was facing the same error as  #11 while using 'hvg' 

Not entirely sure what resolved the 'hvg' issue but in the current version of my script I am using an SCE object and filter out zero expression features.

```
set.seed(123456)

library(psupertime)
library(SingleCellExperiment)

# Import labels
y <- read.delim('inputs/labels.tsv', header = FALSE, sep = "\t")[2]
y <- apply(y, 1, function(x) substring(x,2))
#y <- factor(y) <- This solves the error with nfolds

# Import data and convert to SCE object
data <- read.delim('inputs/data.tsv', header = TRUE, row.names=1, sep = "\t")
sce <- SingleCellExperiment(assay=list(counts = as.matrix(data)))

# Filter zero expression features and logtransforming
keep_feature <- rowSums(counts(sce) > 0) > 0
sce <- sce[keep_feature,]
sce <- normalize(sce)

# Run psupertime
result <- psupertime(x = sce, y = y, sel_genes = 'hvg', smooth=TRUE, n_folds = 3)

# Plot results
train_stats <- plot_train_results(result)
relevant_genes <- plot_identified_genes_over_psupertime(result, n_to_plot = 100)

**Comment by wmacnair** [comment]
I think this is caused by your data being a bit weirdly scaled. `psupertime` uses functionality from `scran` to identify highly variable genes (HVGs). The `scran` function `trendVar` excludes any genes with means less than 0.1, and in the case of your data that turns out to be all of them...! You can test this by running this code:
```
psupertime(x = as.matrix(data*1e3, rownames = TRUE), y = labels, sel_genes = 'hvg', smooth=TRUE, n_folds = 3)
```
which runs fine (for me, at least). My guess is that you've done something like divided your log expression values by 1e3 at some point. Could that be the case?

In any case, I've added a more informative error message. Please check and reopen if it hasn't fixed it!
