### ISSUE TITLE
Cell identifiers not included in the results object

### ISSUE THREAD

**Issue by aron0093** [wmacnair/psupertime#14]
Using a SIngleCellExperiment object as input for psupertime I was interested in the beta values of relevant genes and pseudotime values per cell. 

The result object doesn't include the original cell identifiers and while I expect the new index to correspond to the original i.e. the same ordering it would be nice to have the original cell identifiers present under result$proj_dt similar to how gene identifiers are present under result$beta_dt

**Comment by wmacnair** [comment]
Hey, thanks for pointing this out. Your assumption is correct that they do have the same ordering, but I can add the cell ids to proj_dt as well.
