### ISSUE TITLE
Scoring on gene associations with groups

### ISSUE THREAD

**Issue by cstill1992** [wmacnair/psupertime#15]
Hi,

Thanks for the awesome package. I had a quick question about the psupertime_go_analysis. It groups genes into clusters based on similarity of expression. My question is, are there any scores related to a gene's association with a certain cluster? If so, how can I access those scores? I haven't been able to find any.

Thanks,
Chris

**Comment by wmacnair** [comment]
Hi Chris

Sorry it's taken me a while to get back to you.

So to make sure I've understood your question correctly: you're wondering if there's some way of quantifying how strongly a gene has been placed in a given cluster, and not the GO association, is that right?

If you look inside the `psupertime_go_analysis` function, you'll see that `psupertime` is just doing very standard hierarchical clustering (using the function `hclust` from the `fastcluster` package). A fairly standard approach to quantify strength of assocation would be to use [silhouette width](https://en.wikipedia.org/wiki/Silhouette_(clustering)): this tells you how close a gene is to its cluster, relative to other clusters. I expect there are multiple options for how to do this; one option is the [cluster](https://stat.ethz.ch/R-manual/R-devel/library/cluster/html/silhouette.html) package. At present `psupertime` doesn't give this as an output though, so you'd kind of have to hack into the function yourself.

Hope that helps! 

(The approach for clustering genes and doing GO analysis I implemented here isn't particularly sophisticated, but should illustrate the sort of thing you can do. You could definitely do this in a fancier way if you wanted to.)

Let me know if you have any further questions :)

Best
Will

**Comment by wmacnair** [comment]
Closing this, but happy to reopen if you'd like to discuss it more .
Will
