### ISSUE TITLE
tf_list.rda only formatted for mouse gene symbols

### ISSUE THREAD

**Issue by dpcook** [wmacnair/psupertime#3]
Hi again! Minor detail. Currently tf_list.rda is formatted to only be compatible with mouse gene symbols (ie. capitalized first letter, rest lowercase). Could be valuable to include a species option and provide an alternative list, or do some automatic check from the gene names in the expression matrix.

If you don't want to implement it, it's fairly straight forward for users to deal with, so I don't think this is a big issue at all--just wanted to point it out.

David

**Comment by wmacnair** [comment]
There's always so much to learn about genes... ;)

Thanks for pointing this out. I'll look into doing this. I could have `psupertime` make a guess on the basis of matching genes, or include an explicit species option.

Will

**Comment by wmacnair** [comment]
Fixed in commit which fixed #2
