### ISSUE TITLE
Error with labels

### ISSUE THREAD

**Issue by DanLesman** [wmacnair/psupertime#5]
Hi,

I am having an issue with the labels or y value when calling psupertime. I am getting an error during fold 1 that reads: Error in rep(0, n * (k - 1)) : invalid 'times' argument

I was able to fix this previously by changing my labels from doubles to integers; however, I am working with a new dataset and I am getting this error even with integers.

Is there something I am doing wrong or overlooking?

Best,
Dan

**Comment by wmacnair** [comment]
Hi Dan

Sorry for the slow response - I missed this somehow... 

For the labels, `psupertime` expects to receive a factor as input. Could you try something like
```
psuper_obj = psupertime(x, factor(labels))
```
and let me know if that works? 

Hopefully that will fix it. I think I've added some kind of conversion to factor in the code, but I should double-check it.

Cheers
Will

**Comment by wmacnair** [comment]
Hi @DanLesman 

Did you find out what the bug was? Did converting to factor fix it?

Cheers
Will

**Comment by wmacnair** [comment]
Closing this issue - happy to reopen if you post more details.
Will
