### ISSUE TITLE
Single gene plotting gives NA for label

### ISSUE THREAD

**Issue by topherconley** [wmacnair/psupertime#6]
I found a small improvement at https://github.com/wmacnair/psupertime/blob/0896d2d96805e10cc562327dd772ab06c15a6f37/R/psupertime_plots.R#L353)

If you add `drop = FALSE` when subsetting single genes, you will not get an 'NA' for the gene's symbol. 

The change I am proposing is: 

`plot_wide   = cbind(proj_dt, data.table(x_data[, extra_genes, drop = FALSE]))`
  
By the way, so far I really like this package.

**Comment by wmacnair** [comment]
Hi, thanks for catching this. I've added your fix twice, so now both  `plot_identified_genes_over_psupertime` and `plot_specified_genes_over_psupertime` allow plotting of one gene.

Glad you're finding it useful! Please do keep on making suggestions :)

Cheers
Will
