### ISSUE TITLE
Sanitizing labels 

### ISSUE THREAD

**Issue by topherconley** [wmacnair/psupertime#7]
If by some mistake the label input `y` contains missing values in `psupertime::psupertime`,  this error from `glmnet` occurs.

`Error in if (!all(o)) { : missing value where TRUE/FALSE needed`

Perhaps something like would help users. 

```r
if (any(is.na(y)) { 
  stop('Input y contains missing values.')
}
```

**Comment by wmacnair** [comment]
Hi @topherconley 

Thanks for reporting this - somewhat belatedly getting round to addressing it... I'll add this to the function `check_params`.

Cheers!
Will
