### ISSUE TITLE
vignette not available

### ISSUE THREAD

**Issue by plger** [wmacnair/psupertime#9]
The `browseVignettes(package = 'psupertime')` of the readme returns
```
No vignettes found by browseVignettes(package = "psupertime")
```

`vignette("psuper_intro")` didn't work either.

(Installed via `BiocManager::install("wmacnair/psupertime")`)

**Comment by wmacnair** [comment]
I think this is just a matter of installing via `devtools` with `build_vignettes=TRUE`. Try that, and if it doesn't work we can reopen.
